### PR TITLE
Added support for merge_vars and global_merge_vars

### PR DESCRIPTION
**Pull request by dancingshell**
~~EDIT: closing this pr and going to open another with a cleaner API for merge_vars~~
EDIT: reopened same PR with updated API. <b>ready for review</b>

Mandrill merge_vars are supported.
- `merge_vars` and `global_merge_vars` for single and multiple recipients
- updated readme

### CODE REVIEW

**Comment by fabien** [comment]
@dancingshell thanks for your contribution

**Comment by dancingshell** [comment]
@fabien thanks for incorporating my changes. What do you think about releasing a new tag?

**Comment by dancingshell** [comment]
@fabien can you bump the version? If we are following semver would be`v0.1.0`. The readme is now not in sync with what you get from npm

**Comment by fabien** [comment]
@dancingshell I bumped the version. However, I don't know what you mean regarding the readme and npm. NPM still refers to `github.com/evenemento/lb-connector-mandrill` unfortunately, and to be honest I am not actively using `lb-connector-mandrill` (this repo) myself anymore.

If you feel like taking over the repo, just let me know!

**Comment by dancingshell** [comment]
@fabien I would be happy to take over the repo, since I am working on a project that is using it. Feel free to transfer the repo to my account or add me as repo owner. Thanks.

**Comment by dancingshell** [comment]
@fabien also do you have npm access?

**Comment by fabien** [comment]
@dancingshell I sent you a transfer confirmation request. Unfortunately, I don't have any access to the current npm entry for this module. You should check with @mchmielarski perhaps he can transfer his npm ownership?

**Pull request merged**
